import type { Region, WhiskyType } from "./types";

export const WHISKY_SEED: {
  name: string;
  distillery: string;
  region: Region;
  type: WhiskyType;
  age: number | null;
  abv: number;
  caskStrength: boolean;
}[] = [
  // ─── Islay ──────────────────────────────────────────────────────────────────
  { name: "Lagavulin 16", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 16, abv: 43, caskStrength: false },
  { name: "Lagavulin 8", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 8, abv: 48, caskStrength: false },
  { name: "Lagavulin 12 Cask Strength", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 12, abv: 56.4, caskStrength: true },
  { name: "Lagavulin Distillers Edition", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Laphroaig 10", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Laphroaig 10 Cask Strength", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 10, abv: 58.6, caskStrength: true },
  { name: "Laphroaig Quarter Cask", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Laphroaig Triple Wood", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Laphroaig 25", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 25, abv: 51.4, caskStrength: true },
  { name: "Laphroaig Lore", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Ardbeg 10", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Ardbeg Uigeadail", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 54.2, caskStrength: true },
  { name: "Ardbeg Corryvreckan", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 57.1, caskStrength: true },
  { name: "Ardbeg An Oa", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 46.6, caskStrength: false },
  { name: "Ardbeg Wee Beastie 5", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 5, abv: 47.4, caskStrength: false },
  { name: "Ardbeg Traigh Bhan 19", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 19, abv: 46.2, caskStrength: false },
  { name: "Ardbeg Supernova", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 53.8, caskStrength: true },
  { name: "Bowmore 12", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Bowmore 15 Darkest", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Bowmore 18", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Bowmore 25", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Bruichladdich The Classic Laddie", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bruichladdich Islay Barley", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bruichladdich Port Charlotte 10", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 10, abv: 50, caskStrength: false },
  { name: "Bruichladdich Port Charlotte MRC:01", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 59.2, caskStrength: true },
  { name: "Bruichladdich Octomore 14.1", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 5, abv: 59.6, caskStrength: true },
  { name: "Bruichladdich Octomore 14.3", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 5, abv: 61.4, caskStrength: true },
  { name: "Caol Ila 12", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Caol Ila 18", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Caol Ila Cask Strength", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: null, abv: 61.6, caskStrength: true },
  { name: "Kilchoman Machir Bay", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman Sanaig", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman Loch Gorm", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman 100% Islay", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bunnahabhain 12", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: 12, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain 18", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: 18, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain Stiuireadair", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: null, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain Toiteach A Dha", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: null, abv: 46.3, caskStrength: false },
  { name: "Ardnahoe Inaugural Release", distillery: "Ardnahoe", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },

  // ─── Speyside ───────────────────────────────────────────────────────────────
  { name: "Macallan 12 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Macallan 12 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Macallan 15 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Macallan 18 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Macallan 18 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Macallan 25 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Macallan Edition No.1", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Macallan Rare Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Macallan Classic Cut", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 55, caskStrength: true },
  { name: "Macallan A Night on Earth", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Glenfiddich 12", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Glenfiddich 15 Solera", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Glenfiddich 18", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 18, abv: 40, caskStrength: false },
  { name: "Glenfiddich 21 Reserva Rum Cask", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "Glenfiddich Fire & Cane", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Glenlivet 12", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Glenlivet 15 French Oak", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Glenlivet 18", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 18, abv: 40, caskStrength: false },
  { name: "Glenlivet Nadurra First Fill", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: null, abv: 59.1, caskStrength: true },
  { name: "Glenlivet Nadurra Oloroso", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: null, abv: 60.7, caskStrength: true },
  { name: "Balvenie 12 DoubleWood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Balvenie 14 Caribbean Cask", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 14, abv: 43, caskStrength: false },
  { name: "Balvenie 17 DoubleWood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 17, abv: 43, caskStrength: false },
  { name: "Balvenie 21 Portwood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "Balvenie Tun 1509 Batch 8", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: null, abv: 52.2, caskStrength: true },
  { name: "Glenfarclas 10", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glenfarclas 12", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenfarclas 15", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glenfarclas 21", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "Glenfarclas 25", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Glenfarclas 105 Cask Strength", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: null, abv: 60, caskStrength: true },
  { name: "Aberlour 12", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Aberlour 16", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: 16, abv: 40, caskStrength: false },
  { name: "Aberlour A'bunadh", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: null, abv: 61.2, caskStrength: true },
  { name: "Aberlour Casg Annamh", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "GlenDronach 12 Original", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "GlenDronach 15 Revival", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "GlenDronach 18 Allardice", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "GlenDronach 21 Parliament", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 21, abv: 48, caskStrength: false },
  { name: "GlenDronach Cask Strength Batch 12", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: null, abv: 58.2, caskStrength: true },
  { name: "Glengrant 10", distillery: "Glen Grant", region: "Speyside", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glen Grant 18", distillery: "Glen Grant", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Cardhu 12", distillery: "Cardhu", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Craigellachie 13", distillery: "Craigellachie", region: "Speyside", type: "Single Malt", age: 13, abv: 46, caskStrength: false },
  { name: "Cragganmore 12", distillery: "Cragganmore", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Mortlach 16", distillery: "Mortlach", region: "Speyside", type: "Single Malt", age: 16, abv: 43.4, caskStrength: false },
  { name: "Benromach 10", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: 10, abv: 43, caskStrength: false },
  { name: "Benromach Peat Smoke", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Tamdhu 12", distillery: "Tamdhu", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Tamdhu Batch Strength No.7", distillery: "Tamdhu", region: "Speyside", type: "Single Malt", age: null, abv: 57.5, caskStrength: true },
  { name: "BenRiach The Smoky Ten", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "BenRiach The Twelve", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 12, abv: 46, caskStrength: false },

  // ─── Highland ───────────────────────────────────────────────────────────────
  { name: "Highland Park 12 Viking Honour", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Highland Park 18 Viking Pride", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Highland Park 25", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 25, abv: 46, caskStrength: false },
  { name: "Highland Park Cask Strength Release No.4", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: null, abv: 64.3, caskStrength: true },
  { name: "Dalmore 12", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Dalmore 15", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Dalmore 18", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Dalmore Cigar Malt Reserve", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: null, abv: 44, caskStrength: false },
  { name: "Dalmore King Alexander III", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Oban 14", distillery: "Oban", region: "Highland", type: "Single Malt", age: 14, abv: 43, caskStrength: false },
  { name: "Oban Distillers Edition", distillery: "Oban", region: "Highland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Glenmorangie Original 10", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glenmorangie Lasanta 12", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenmorangie Quinta Ruban 14", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Glenmorangie Nectar d'Or 16", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 16, abv: 46, caskStrength: false },
  { name: "Glenmorangie 18", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Glenmorangie Signet", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Clynelish 14", distillery: "Clynelish", region: "Highland", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Talisker 10", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 10, abv: 45.8, caskStrength: false },
  { name: "Talisker 18", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 18, abv: 45.8, caskStrength: false },
  { name: "Talisker Distillers Edition", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 45.8, caskStrength: false },
  { name: "Talisker 25", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 25, abv: 45.8, caskStrength: false },
  { name: "Talisker Storm", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 45.8, caskStrength: false },
  { name: "Old Pulteney 12", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Old Pulteney 15", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Tomatin 12", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Tomatin 18", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Tomatin Cask Strength", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: null, abv: 57.5, caskStrength: true },
  { name: "Edradour 10", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Edradour Caledonia 12", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Ben Nevis 10", distillery: "Ben Nevis", region: "Highland", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Aberfeldy 12", distillery: "Aberfeldy", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Dalwhinnie 15", distillery: "Dalwhinnie", region: "Highland", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Royal Brackla 12", distillery: "Royal Brackla", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Balblair 12", distillery: "Balblair", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "GlenGoyne 12", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "GlenGoyne 21", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "GlenGoyne Cask Strength Batch 10", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: null, abv: 58.9, caskStrength: true },
  { name: "Deanston 12", distillery: "Deanston", region: "Highland", type: "Single Malt", age: 12, abv: 46.3, caskStrength: false },
  { name: "Deanston 18", distillery: "Deanston", region: "Highland", type: "Single Malt", age: 18, abv: 46.3, caskStrength: false },

  // ─── Campbeltown ────────────────────────────────────────────────────────────
  { name: "Springbank 10", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Springbank 12 Cask Strength", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 12, abv: 56.3, caskStrength: true },
  { name: "Springbank 15", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Springbank 18", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Longrow Peated", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Longrow 18", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Hazelburn 10", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Glen Scotia 15", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glen Scotia Victoriana", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: null, abv: 54.2, caskStrength: true },
  { name: "Glen Scotia Double Cask", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilkerran 12", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Kilkerran 16", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: 16, abv: 46, caskStrength: false },
  { name: "Kilkerran Heavily Peated", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: null, abv: 57.4, caskStrength: true },

  // ─── Lowland ────────────────────────────────────────────────────────────────
  { name: "Auchentoshan 12", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Auchentoshan Three Wood", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Auchentoshan American Oak", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Glenkinchie 12", distillery: "Glenkinchie", region: "Lowland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenkinchie Distillers Edition", distillery: "Glenkinchie", region: "Lowland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Ailsa Bay Sweet Smoke", distillery: "Ailsa Bay", region: "Lowland", type: "Single Malt", age: null, abv: 48.9, caskStrength: false },

  // ─── Japanese ───────────────────────────────────────────────────────────────
  { name: "Yamazaki 12", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 12, abv: 43, caskStrength: false },
  { name: "Yamazaki 18", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 18, abv: 43, caskStrength: false },
  { name: "Yamazaki 25", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 25, abv: 43, caskStrength: false },
  { name: "Yamazaki Distiller's Reserve", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hakushu 12", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: 12, abv: 43, caskStrength: false },
  { name: "Hakushu 18", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: 18, abv: 43, caskStrength: false },
  { name: "Hakushu Distiller's Reserve", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hibiki Japanese Harmony", distillery: "Suntory", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hibiki 17", distillery: "Suntory", region: "Japanese", type: "Japanese", age: 17, abv: 43, caskStrength: false },
  { name: "Hibiki 21", distillery: "Suntory", region: "Japanese", type: "Japanese", age: 21, abv: 43, caskStrength: false },
  { name: "Nikka From The Barrel", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 51.4, caskStrength: false },
  { name: "Nikka Coffey Grain", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Coffey Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Taketsuru Pure Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Nikka Yoichi Single Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Yoichi 10", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 10, abv: 45, caskStrength: false },
  { name: "Nikka Miyagikyo Single Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Chichibu The Peated", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 53.5, caskStrength: true },
  { name: "Chichibu IPA Cask Finish", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 57.5, caskStrength: true },
  { name: "Chichibu On The Way", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 58.5, caskStrength: true },
  { name: "Mars Iwai Tradition", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Mars Komagatake", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 48, caskStrength: false },
  { name: "Akashi Single Malt", distillery: "White Oak", region: "Japanese", type: "Japanese", age: null, abv: 46, caskStrength: false },
  { name: "Togouchi Premium", distillery: "Chugoku Jozo", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Suntory Toki", distillery: "Suntory", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Nikka Days", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Kaiyo Mizunara Oak", distillery: "Kaiyo", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Kaiyo Cask Strength", distillery: "Kaiyo", region: "Japanese", type: "Japanese", age: null, abv: 53, caskStrength: true },

  // ─── Bourbon ────────────────────────────────────────────────────────────────
  { name: "Maker's Mark", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Maker's Mark Cask Strength", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 55.75, caskStrength: true },
  { name: "Maker's Mark 46", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 47, caskStrength: false },
  { name: "Buffalo Trace", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Eagle Rare 10", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 10, abv: 45, caskStrength: false },
  { name: "Blanton's Single Barrel", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 46.5, caskStrength: false },
  { name: "E.H. Taylor Small Batch", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 50, caskStrength: false },
  { name: "Stagg Jr.", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 65.45, caskStrength: true },
  { name: "Woodford Reserve", distillery: "Woodford Reserve", region: "Bourbon", type: "Bourbon", age: null, abv: 43.2, caskStrength: false },
  { name: "Woodford Reserve Double Oaked", distillery: "Woodford Reserve", region: "Bourbon", type: "Bourbon", age: null, abv: 43.2, caskStrength: false },
  { name: "Wild Turkey 101", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 50.5, caskStrength: false },
  { name: "Wild Turkey Rare Breed", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 58.4, caskStrength: true },
  { name: "Russell's Reserve 10", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: 10, abv: 45, caskStrength: false },
  { name: "Russell's Reserve Single Barrel", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 55, caskStrength: false },
  { name: "Four Roses Single Barrel", distillery: "Four Roses", region: "Bourbon", type: "Bourbon", age: null, abv: 50, caskStrength: false },
  { name: "Four Roses Small Batch Select", distillery: "Four Roses", region: "Bourbon", type: "Bourbon", age: null, abv: 52, caskStrength: false },
  { name: "Knob Creek 9", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: 9, abv: 50, caskStrength: false },
  { name: "Knob Creek Single Barrel Reserve", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: 9, abv: 60, caskStrength: true },
  { name: "Booker's Bourbon", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: null, abv: 62.95, caskStrength: true },
  { name: "Jim Beam Black Extra-Aged", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: null, abv: 43, caskStrength: false },
  { name: "Elijah Craig Small Batch", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 47, caskStrength: false },
  { name: "Elijah Craig Barrel Proof", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 60.1, caskStrength: true },
  { name: "Evan Williams Single Barrel", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 43.3, caskStrength: false },
  { name: "Bulleit Bourbon", distillery: "Bulleit", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Bulleit Rye", distillery: "Bulleit", region: "Bourbon", type: "Rye", age: null, abv: 45, caskStrength: false },
  { name: "Rittenhouse Rye BiB", distillery: "Heaven Hill", region: "Bourbon", type: "Rye", age: null, abv: 50, caskStrength: false },
  { name: "WhistlePig 10 Rye", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: 10, abv: 50, caskStrength: false },
  { name: "Michter's US*1 Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: null, abv: 45.7, caskStrength: false },
  { name: "Michter's US*1 Rye", distillery: "Michter's", region: "Bourbon", type: "Rye", age: null, abv: 42.4, caskStrength: false },

  // ─── Irish ──────────────────────────────────────────────────────────────────
  { name: "Jameson", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Jameson Black Barrel", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Jameson 18", distillery: "Midleton", region: "Irish", type: "Irish", age: 18, abv: 40, caskStrength: false },
  { name: "Redbreast 12", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 40, caskStrength: false },
  { name: "Redbreast 12 Cask Strength", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 58.6, caskStrength: true },
  { name: "Redbreast 15", distillery: "Midleton", region: "Irish", type: "Irish", age: 15, abv: 46, caskStrength: false },
  { name: "Redbreast 21", distillery: "Midleton", region: "Irish", type: "Irish", age: 21, abv: 46, caskStrength: false },
  { name: "Green Spot", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Yellow Spot", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 46, caskStrength: false },
  { name: "Bushmills 10", distillery: "Bushmills", region: "Irish", type: "Irish", age: 10, abv: 40, caskStrength: false },
  { name: "Bushmills 16 Three Wood", distillery: "Bushmills", region: "Irish", type: "Irish", age: 16, abv: 40, caskStrength: false },
  { name: "Bushmills 21", distillery: "Bushmills", region: "Irish", type: "Irish", age: 21, abv: 40, caskStrength: false },
  { name: "Powers John's Lane 12", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 46, caskStrength: false },
  { name: "Connemara Peated", distillery: "Cooley", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Connemara Cask Strength", distillery: "Cooley", region: "Irish", type: "Irish", age: null, abv: 57.9, caskStrength: true },
  { name: "Teeling Single Grain", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Teeling Single Malt", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Writers' Tears Copper Pot", distillery: "Walsh", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },

  // ─── Indian ─────────────────────────────────────────────────────────────────
  { name: "Amrut Fusion", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Amrut Indian Single Malt", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Amrut Peated Indian Single Malt", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Amrut Peated Cask Strength", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 62.8, caskStrength: true },
  { name: "Amrut Naarangi", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Paul John Brilliance", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Edited", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Bold", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Peated Select Cask", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 55.5, caskStrength: true },
  { name: "Rampur Indian Single Malt", distillery: "Rampur", region: "Indian", type: "Single Malt", age: null, abv: 43, caskStrength: false },

  // ─── Blends & Blended Malts ─────────────────────────────────────────────────
  { name: "Johnnie Walker Black Label 12", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Johnnie Walker Green Label 15", distillery: "Johnnie Walker", region: "Other", type: "Blended Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Johnnie Walker Gold Label Reserve", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Johnnie Walker Blue Label", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Monkey Shoulder", distillery: "William Grant & Sons", region: "Speyside", type: "Blended Malt", age: null, abv: 40, caskStrength: false },
  { name: "Compass Box Great King Street Artist's Blend", distillery: "Compass Box", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box Peat Monster", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box Spice Tree", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box Hedonism", distillery: "Compass Box", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box The Story of the Spaniard", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 43, caskStrength: false },
  { name: "Chivas Regal 12", distillery: "Chivas", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Chivas Regal 18", distillery: "Chivas", region: "Other", type: "Blended", age: 18, abv: 40, caskStrength: false },
  { name: "Dewar's 12", distillery: "Dewar's", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Ballantine's 17", distillery: "Ballantine's", region: "Other", type: "Blended", age: 17, abv: 40, caskStrength: false },
  { name: "Famous Grouse", distillery: "Edrington", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Naked Grouse", distillery: "Edrington", region: "Other", type: "Blended Malt", age: null, abv: 40, caskStrength: false },
  { name: "Big Peat", distillery: "Douglas Laing", region: "Islay", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Big Peat Cask Strength Christmas Edition", distillery: "Douglas Laing", region: "Islay", type: "Blended Malt", age: null, abv: 54.6, caskStrength: true },
  { name: "Scallywag", distillery: "Douglas Laing", region: "Speyside", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Timorous Beastie", distillery: "Douglas Laing", region: "Highland", type: "Blended Malt", age: null, abv: 46.8, caskStrength: false },
  { name: "Rock Island", distillery: "Douglas Laing", region: "Highland", type: "Blended Malt", age: null, abv: 46.8, caskStrength: false },
];
