import type { Region, WhiskyType } from "./types";

export const WHISKY_SEED: {
  name: string;
  distillery: string;
  region: Region;
  type: WhiskyType;
  age: number | null;
  abv: number;
  caskStrength: boolean;
}[] = [
  // ─── Islay ──────────────────────────────────────────────────────────────────
  { name: "Lagavulin 16", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 16, abv: 43, caskStrength: false },
  { name: "Lagavulin 8", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 8, abv: 48, caskStrength: false },
  { name: "Lagavulin 12 Cask Strength", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: 12, abv: 56.4, caskStrength: true },
  { name: "Lagavulin Distillers Edition", distillery: "Lagavulin", region: "Islay", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Laphroaig 10", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Laphroaig 10 Cask Strength", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 10, abv: 58.6, caskStrength: true },
  { name: "Laphroaig Quarter Cask", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Laphroaig Triple Wood", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Laphroaig 25", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: 25, abv: 51.4, caskStrength: true },
  { name: "Laphroaig Lore", distillery: "Laphroaig", region: "Islay", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Ardbeg 10", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Ardbeg Uigeadail", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 54.2, caskStrength: true },
  { name: "Ardbeg Corryvreckan", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 57.1, caskStrength: true },
  { name: "Ardbeg An Oa", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 46.6, caskStrength: false },
  { name: "Ardbeg Wee Beastie 5", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 5, abv: 47.4, caskStrength: false },
  { name: "Ardbeg Traigh Bhan 19", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: 19, abv: 46.2, caskStrength: false },
  { name: "Ardbeg Supernova", distillery: "Ardbeg", region: "Islay", type: "Single Malt", age: null, abv: 53.8, caskStrength: true },
  { name: "Bowmore 12", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Bowmore 15 Darkest", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Bowmore 18", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Bowmore 25", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Bruichladdich The Classic Laddie", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bruichladdich Islay Barley", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bruichladdich Port Charlotte 10", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 10, abv: 50, caskStrength: false },
  { name: "Bruichladdich Port Charlotte MRC:01", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: null, abv: 59.2, caskStrength: true },
  { name: "Bruichladdich Octomore 14.1", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 5, abv: 59.6, caskStrength: true },
  { name: "Bruichladdich Octomore 14.3", distillery: "Bruichladdich", region: "Islay", type: "Single Malt", age: 5, abv: 61.4, caskStrength: true },
  { name: "Caol Ila 12", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Caol Ila 18", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Caol Ila Cask Strength", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: null, abv: 61.6, caskStrength: true },
  { name: "Kilchoman Machir Bay", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman Sanaig", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman Loch Gorm", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilchoman 100% Islay", distillery: "Kilchoman", region: "Islay", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Bunnahabhain 12", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: 12, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain 18", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: 18, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain Stiuireadair", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: null, abv: 46.3, caskStrength: false },
  { name: "Bunnahabhain Toiteach A Dha", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: null, abv: 46.3, caskStrength: false },
  { name: "Ardnahoe Inaugural Release", distillery: "Ardnahoe", region: "Islay", type: "Single Malt", age: null, abv: 46, caskStrength: false },

  // ─── Speyside ───────────────────────────────────────────────────────────────
  { name: "Macallan 12 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Macallan 12 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Macallan 15 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Macallan 18 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Macallan 18 Double Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Macallan 25 Sherry Oak", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Macallan Edition No.1", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Macallan Rare Cask", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Macallan Classic Cut", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 55, caskStrength: true },
  { name: "Macallan A Night on Earth", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Glenfiddich 12", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Glenfiddich 15 Solera", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Glenfiddich 18", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 18, abv: 40, caskStrength: false },
  { name: "Glenfiddich 21 Reserva Rum Cask", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "Glenfiddich Fire & Cane", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Glenlivet 12", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Glenlivet 15 French Oak", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Glenlivet 18", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: 18, abv: 40, caskStrength: false },
  { name: "Glenlivet Nadurra First Fill", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: null, abv: 59.1, caskStrength: true },
  { name: "Glenlivet Nadurra Oloroso", distillery: "Glenlivet", region: "Speyside", type: "Single Malt", age: null, abv: 60.7, caskStrength: true },
  { name: "Balvenie 12 DoubleWood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Balvenie 14 Caribbean Cask", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 14, abv: 43, caskStrength: false },
  { name: "Balvenie 17 DoubleWood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 17, abv: 43, caskStrength: false },
  { name: "Balvenie 21 Portwood", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "Balvenie Tun 1509 Batch 8", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: null, abv: 52.2, caskStrength: true },
  { name: "Glenfarclas 10", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glenfarclas 12", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenfarclas 15", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glenfarclas 21", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "Glenfarclas 25", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: 25, abv: 43, caskStrength: false },
  { name: "Glenfarclas 105 Cask Strength", distillery: "Glenfarclas", region: "Speyside", type: "Single Malt", age: null, abv: 60, caskStrength: true },
  { name: "Aberlour 12", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Aberlour 16", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: 16, abv: 40, caskStrength: false },
  { name: "Aberlour A'bunadh", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: null, abv: 61.2, caskStrength: true },
  { name: "Aberlour Casg Annamh", distillery: "Aberlour", region: "Speyside", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "GlenDronach 12 Original", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "GlenDronach 15 Revival", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "GlenDronach 18 Allardice", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "GlenDronach 21 Parliament", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: 21, abv: 48, caskStrength: false },
  { name: "GlenDronach Cask Strength Batch 12", distillery: "GlenDronach", region: "Speyside", type: "Single Malt", age: null, abv: 58.2, caskStrength: true },
  { name: "Glengrant 10", distillery: "Glen Grant", region: "Speyside", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glen Grant 18", distillery: "Glen Grant", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Cardhu 12", distillery: "Cardhu", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Craigellachie 13", distillery: "Craigellachie", region: "Speyside", type: "Single Malt", age: 13, abv: 46, caskStrength: false },
  { name: "Cragganmore 12", distillery: "Cragganmore", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Mortlach 16", distillery: "Mortlach", region: "Speyside", type: "Single Malt", age: 16, abv: 43.4, caskStrength: false },
  { name: "Benromach 10", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: 10, abv: 43, caskStrength: false },
  { name: "Benromach Peat Smoke", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Tamdhu 12", distillery: "Tamdhu", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Tamdhu Batch Strength No.7", distillery: "Tamdhu", region: "Speyside", type: "Single Malt", age: null, abv: 57.5, caskStrength: true },
  { name: "BenRiach The Smoky Ten", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "BenRiach The Twelve", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 12, abv: 46, caskStrength: false },

  // ─── Highland ───────────────────────────────────────────────────────────────
  { name: "Highland Park 12 Viking Honour", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Highland Park 18 Viking Pride", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Highland Park 25", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: 25, abv: 46, caskStrength: false },
  { name: "Highland Park Cask Strength Release No.4", distillery: "Highland Park", region: "Highland", type: "Single Malt", age: null, abv: 64.3, caskStrength: true },
  { name: "Dalmore 12", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Dalmore 15", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Dalmore 18", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Dalmore Cigar Malt Reserve", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: null, abv: 44, caskStrength: false },
  { name: "Dalmore King Alexander III", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Oban 14", distillery: "Oban", region: "Highland", type: "Single Malt", age: 14, abv: 43, caskStrength: false },
  { name: "Oban Distillers Edition", distillery: "Oban", region: "Highland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Glenmorangie Original 10", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Glenmorangie Lasanta 12", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenmorangie Quinta Ruban 14", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Glenmorangie Nectar d'Or 16", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 16, abv: 46, caskStrength: false },
  { name: "Glenmorangie 18", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Glenmorangie Signet", distillery: "Glenmorangie", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Clynelish 14", distillery: "Clynelish", region: "Highland", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Talisker 10", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 10, abv: 45.8, caskStrength: false },
  { name: "Talisker 18", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 18, abv: 45.8, caskStrength: false },
  { name: "Talisker Distillers Edition", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 45.8, caskStrength: false },
  { name: "Talisker 25", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 25, abv: 45.8, caskStrength: false },
  { name: "Talisker Storm", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 45.8, caskStrength: false },
  { name: "Old Pulteney 12", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Old Pulteney 15", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Tomatin 12", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Tomatin 18", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Tomatin Cask Strength", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: null, abv: 57.5, caskStrength: true },
  { name: "Edradour 10", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Edradour Caledonia 12", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Ben Nevis 10", distillery: "Ben Nevis", region: "Highland", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Aberfeldy 12", distillery: "Aberfeldy", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Dalwhinnie 15", distillery: "Dalwhinnie", region: "Highland", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Royal Brackla 12", distillery: "Royal Brackla", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Balblair 12", distillery: "Balblair", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "GlenGoyne 12", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "GlenGoyne 21", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "GlenGoyne Cask Strength Batch 10", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: null, abv: 58.9, caskStrength: true },
  { name: "Deanston 12", distillery: "Deanston", region: "Highland", type: "Single Malt", age: 12, abv: 46.3, caskStrength: false },
  { name: "Deanston 18", distillery: "Deanston", region: "Highland", type: "Single Malt", age: 18, abv: 46.3, caskStrength: false },

  // ─── Campbeltown ────────────────────────────────────────────────────────────
  { name: "Springbank 10", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Springbank 12 Cask Strength", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 12, abv: 56.3, caskStrength: true },
  { name: "Springbank 15", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Springbank 18", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Longrow Peated", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Longrow 18", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Hazelburn 10", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Glen Scotia 15", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glen Scotia Victoriana", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: null, abv: 54.2, caskStrength: true },
  { name: "Glen Scotia Double Cask", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kilkerran 12", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Kilkerran 16", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: 16, abv: 46, caskStrength: false },
  { name: "Kilkerran Heavily Peated", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: null, abv: 57.4, caskStrength: true },

  // ─── Lowland ────────────────────────────────────────────────────────────────
  { name: "Auchentoshan 12", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Auchentoshan Three Wood", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Auchentoshan American Oak", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Glenkinchie 12", distillery: "Glenkinchie", region: "Lowland", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Glenkinchie Distillers Edition", distillery: "Glenkinchie", region: "Lowland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Ailsa Bay Sweet Smoke", distillery: "Ailsa Bay", region: "Lowland", type: "Single Malt", age: null, abv: 48.9, caskStrength: false },

  // ─── Japanese ───────────────────────────────────────────────────────────────
  { name: "Yamazaki 12", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 12, abv: 43, caskStrength: false },
  { name: "Yamazaki 18", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 18, abv: 43, caskStrength: false },
  { name: "Yamazaki 25", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: 25, abv: 43, caskStrength: false },
  { name: "Yamazaki Distiller's Reserve", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hakushu 12", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: 12, abv: 43, caskStrength: false },
  { name: "Hakushu 18", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: 18, abv: 43, caskStrength: false },
  { name: "Hakushu Distiller's Reserve", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hibiki Japanese Harmony", distillery: "Suntory", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Hibiki 17", distillery: "Suntory", region: "Japanese", type: "Japanese", age: 17, abv: 43, caskStrength: false },
  { name: "Hibiki 21", distillery: "Suntory", region: "Japanese", type: "Japanese", age: 21, abv: 43, caskStrength: false },
  { name: "Nikka From The Barrel", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 51.4, caskStrength: false },
  { name: "Nikka Coffey Grain", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Coffey Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Taketsuru Pure Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Nikka Yoichi Single Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Nikka Yoichi 10", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 10, abv: 45, caskStrength: false },
  { name: "Nikka Miyagikyo Single Malt", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 45, caskStrength: false },
  { name: "Chichibu The Peated", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 53.5, caskStrength: true },
  { name: "Chichibu IPA Cask Finish", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 57.5, caskStrength: true },
  { name: "Chichibu On The Way", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 58.5, caskStrength: true },
  { name: "Mars Iwai Tradition", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Mars Komagatake", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 48, caskStrength: false },
  { name: "Akashi Single Malt", distillery: "White Oak", region: "Japanese", type: "Japanese", age: null, abv: 46, caskStrength: false },
  { name: "Togouchi Premium", distillery: "Chugoku Jozo", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Suntory Toki", distillery: "Suntory", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Nikka Days", distillery: "Nikka", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Kaiyo Mizunara Oak", distillery: "Kaiyo", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Kaiyo Cask Strength", distillery: "Kaiyo", region: "Japanese", type: "Japanese", age: null, abv: 53, caskStrength: true },

  // ─── Bourbon ────────────────────────────────────────────────────────────────
  { name: "Maker's Mark", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Maker's Mark Cask Strength", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 55.75, caskStrength: true },
  { name: "Maker's Mark 46", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 47, caskStrength: false },
  { name: "Buffalo Trace", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Eagle Rare 10", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 10, abv: 45, caskStrength: false },
  { name: "Blanton's Single Barrel", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 46.5, caskStrength: false },
  { name: "E.H. Taylor Small Batch", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 50, caskStrength: false },
  { name: "Stagg Jr.", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 65.45, caskStrength: true },
  { name: "Woodford Reserve", distillery: "Woodford Reserve", region: "Bourbon", type: "Bourbon", age: null, abv: 43.2, caskStrength: false },
  { name: "Woodford Reserve Double Oaked", distillery: "Woodford Reserve", region: "Bourbon", type: "Bourbon", age: null, abv: 43.2, caskStrength: false },
  { name: "Wild Turkey 101", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 50.5, caskStrength: false },
  { name: "Wild Turkey Rare Breed", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 58.4, caskStrength: true },
  { name: "Russell's Reserve 10", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: 10, abv: 45, caskStrength: false },
  { name: "Russell's Reserve Single Barrel", distillery: "Wild Turkey", region: "Bourbon", type: "Bourbon", age: null, abv: 55, caskStrength: false },
  { name: "Four Roses Single Barrel", distillery: "Four Roses", region: "Bourbon", type: "Bourbon", age: null, abv: 50, caskStrength: false },
  { name: "Four Roses Small Batch Select", distillery: "Four Roses", region: "Bourbon", type: "Bourbon", age: null, abv: 52, caskStrength: false },
  { name: "Knob Creek 9", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: 9, abv: 50, caskStrength: false },
  { name: "Knob Creek Single Barrel Reserve", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: 9, abv: 60, caskStrength: true },
  { name: "Booker's Bourbon", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: null, abv: 62.95, caskStrength: true },
  { name: "Jim Beam Black Extra-Aged", distillery: "Jim Beam", region: "Bourbon", type: "Bourbon", age: null, abv: 43, caskStrength: false },
  { name: "Elijah Craig Small Batch", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 47, caskStrength: false },
  { name: "Elijah Craig Barrel Proof", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 60.1, caskStrength: true },
  { name: "Evan Williams Single Barrel", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: null, abv: 43.3, caskStrength: false },
  { name: "Bulleit Bourbon", distillery: "Bulleit", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Bulleit Rye", distillery: "Bulleit", region: "Bourbon", type: "Rye", age: null, abv: 45, caskStrength: false },
  { name: "Rittenhouse Rye BiB", distillery: "Heaven Hill", region: "Bourbon", type: "Rye", age: null, abv: 50, caskStrength: false },
  { name: "WhistlePig 10 Rye", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: 10, abv: 50, caskStrength: false },
  { name: "Michter's US*1 Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: null, abv: 45.7, caskStrength: false },
  { name: "Michter's US*1 Rye", distillery: "Michter's", region: "Bourbon", type: "Rye", age: null, abv: 42.4, caskStrength: false },

  // ─── Irish ──────────────────────────────────────────────────────────────────
  { name: "Jameson", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Jameson Black Barrel", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Jameson 18", distillery: "Midleton", region: "Irish", type: "Irish", age: 18, abv: 40, caskStrength: false },
  { name: "Redbreast 12", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 40, caskStrength: false },
  { name: "Redbreast 12 Cask Strength", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 58.6, caskStrength: true },
  { name: "Redbreast 15", distillery: "Midleton", region: "Irish", type: "Irish", age: 15, abv: 46, caskStrength: false },
  { name: "Redbreast 21", distillery: "Midleton", region: "Irish", type: "Irish", age: 21, abv: 46, caskStrength: false },
  { name: "Green Spot", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Yellow Spot", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 46, caskStrength: false },
  { name: "Bushmills 10", distillery: "Bushmills", region: "Irish", type: "Irish", age: 10, abv: 40, caskStrength: false },
  { name: "Bushmills 16 Three Wood", distillery: "Bushmills", region: "Irish", type: "Irish", age: 16, abv: 40, caskStrength: false },
  { name: "Bushmills 21", distillery: "Bushmills", region: "Irish", type: "Irish", age: 21, abv: 40, caskStrength: false },
  { name: "Powers John's Lane 12", distillery: "Midleton", region: "Irish", type: "Irish", age: 12, abv: 46, caskStrength: false },
  { name: "Connemara Peated", distillery: "Cooley", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Connemara Cask Strength", distillery: "Cooley", region: "Irish", type: "Irish", age: null, abv: 57.9, caskStrength: true },
  { name: "Teeling Single Grain", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Teeling Single Malt", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Writers' Tears Copper Pot", distillery: "Walsh", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },

  // ─── Indian ─────────────────────────────────────────────────────────────────
  { name: "Amrut Fusion", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Amrut Indian Single Malt", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Amrut Peated Indian Single Malt", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Amrut Peated Cask Strength", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 62.8, caskStrength: true },
  { name: "Amrut Naarangi", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Paul John Brilliance", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Edited", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Bold", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Paul John Peated Select Cask", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 55.5, caskStrength: true },
  { name: "Rampur Indian Single Malt", distillery: "Rampur", region: "Indian", type: "Single Malt", age: null, abv: 43, caskStrength: false },

  // ─── Blends & Blended Malts ─────────────────────────────────────────────────
  { name: "Johnnie Walker Black Label 12", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Johnnie Walker Green Label 15", distillery: "Johnnie Walker", region: "Other", type: "Blended Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Johnnie Walker Gold Label Reserve", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Johnnie Walker Blue Label", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Monkey Shoulder", distillery: "William Grant & Sons", region: "Speyside", type: "Blended Malt", age: null, abv: 40, caskStrength: false },
  { name: "Compass Box Great King Street Artist's Blend", distillery: "Compass Box", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box Peat Monster", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box Spice Tree", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box Hedonism", distillery: "Compass Box", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box The Story of the Spaniard", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 43, caskStrength: false },
  { name: "Chivas Regal 12", distillery: "Chivas", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Chivas Regal 18", distillery: "Chivas", region: "Other", type: "Blended", age: 18, abv: 40, caskStrength: false },
  { name: "Dewar's 12", distillery: "Dewar's", region: "Other", type: "Blended", age: 12, abv: 40, caskStrength: false },
  { name: "Ballantine's 17", distillery: "Ballantine's", region: "Other", type: "Blended", age: 17, abv: 40, caskStrength: false },
  { name: "Famous Grouse", distillery: "Edrington", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Naked Grouse", distillery: "Edrington", region: "Other", type: "Blended Malt", age: null, abv: 40, caskStrength: false },
  { name: "Big Peat", distillery: "Douglas Laing", region: "Islay", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Big Peat Cask Strength Christmas Edition", distillery: "Douglas Laing", region: "Islay", type: "Blended Malt", age: null, abv: 54.6, caskStrength: true },
  { name: "Scallywag", distillery: "Douglas Laing", region: "Speyside", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Timorous Beastie", distillery: "Douglas Laing", region: "Highland", type: "Blended Malt", age: null, abv: 46.8, caskStrength: false },
  { name: "Rock Island", distillery: "Douglas Laing", region: "Highland", type: "Blended Malt", age: null, abv: 46.8, caskStrength: false },

  // ─── Independent Bottlings (Scotch) ─────────────────────────────────────────
  { name: "Gordon & MacPhail Linkwood 15", distillery: "Linkwood", region: "Speyside", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Gordon & MacPhail Mortlach 15", distillery: "Mortlach", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Gordon & MacPhail Caol Ila 14", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Gordon & MacPhail Glen Grant 21", distillery: "Glen Grant", region: "Speyside", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "Gordon & MacPhail Longmorn 18", distillery: "Longmorn", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Gordon & MacPhail Benromach 21 Cask Strength", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: 21, abv: 56.5, caskStrength: true },
  { name: "Signatory Vintage Clynelish 12", distillery: "Clynelish", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Signatory Vintage Ben Nevis 13 Cask Strength", distillery: "Ben Nevis", region: "Highland", type: "Single Malt", age: 13, abv: 57.8, caskStrength: true },
  { name: "Signatory Vintage Caol Ila 11 Cask Strength", distillery: "Caol Ila", region: "Islay", type: "Single Malt", age: 11, abv: 58.1, caskStrength: true },
  { name: "Signatory Vintage Ledaig 12", distillery: "Tobermory", region: "Highland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Signatory Vintage Bunnahabhain 11 Cask Strength", distillery: "Bunnahabhain", region: "Islay", type: "Single Malt", age: 11, abv: 59.2, caskStrength: true },
  { name: "Berry Bros Speyside Reserve", distillery: "Berry Bros & Rudd", region: "Speyside", type: "Blended Malt", age: null, abv: 44.2, caskStrength: false },
  { name: "Berry Bros Classic Sherry Cask", distillery: "Berry Bros & Rudd", region: "Speyside", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Berry Bros Islay Reserve", distillery: "Berry Bros & Rudd", region: "Islay", type: "Blended Malt", age: null, abv: 44.2, caskStrength: false },

  // ─── More Speyside ──────────────────────────────────────────────────────────
  { name: "Glencadam 10", distillery: "Glencadam", region: "Speyside", type: "Single Malt", age: 10, abv: 46, caskStrength: false },
  { name: "Glencadam 15", distillery: "Glencadam", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glencadam 21", distillery: "Glencadam", region: "Speyside", type: "Single Malt", age: 21, abv: 46, caskStrength: false },
  { name: "Knockando 12", distillery: "Knockando", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Knockando 18", distillery: "Knockando", region: "Speyside", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Strathisla 12", distillery: "Strathisla", region: "Speyside", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Tomintoul 16", distillery: "Tomintoul", region: "Speyside", type: "Single Malt", age: 16, abv: 40, caskStrength: false },
  { name: "Tomintoul Peaty Tang", distillery: "Tomintoul", region: "Speyside", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Tomintoul Tlath", distillery: "Tomintoul", region: "Speyside", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Speyburn 10", distillery: "Speyburn", region: "Speyside", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Speyburn 15", distillery: "Speyburn", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Dailuaine 16", distillery: "Dailuaine", region: "Speyside", type: "Single Malt", age: 16, abv: 43, caskStrength: false },
  { name: "Mannochmore 12", distillery: "Mannochmore", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "BenRiach The Twenty One", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 21, abv: 46, caskStrength: false },
  { name: "BenRiach Smoky Twelve", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "BenRiach The Twenty Five", distillery: "BenRiach", region: "Speyside", type: "Single Malt", age: 25, abv: 46, caskStrength: false },
  { name: "Craigellachie 17", distillery: "Craigellachie", region: "Speyside", type: "Single Malt", age: 17, abv: 46, caskStrength: false },
  { name: "Craigellachie 23", distillery: "Craigellachie", region: "Speyside", type: "Single Malt", age: 23, abv: 46, caskStrength: false },
  { name: "Mortlach 12 The Wee Witchie", distillery: "Mortlach", region: "Speyside", type: "Single Malt", age: 12, abv: 43.4, caskStrength: false },
  { name: "Mortlach 20 Cowie's Blue Seal", distillery: "Mortlach", region: "Speyside", type: "Single Malt", age: 20, abv: 43.4, caskStrength: false },
  { name: "Longmorn 16", distillery: "Longmorn", region: "Speyside", type: "Single Malt", age: 16, abv: 48, caskStrength: false },
  { name: "Benromach 15", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "Benromach Cask Strength Vintage", distillery: "Benromach", region: "Speyside", type: "Single Malt", age: null, abv: 57.2, caskStrength: true },
  { name: "Tamdhu 15", distillery: "Tamdhu", region: "Speyside", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Glen Elgin 12", distillery: "Glen Elgin", region: "Speyside", type: "Single Malt", age: 12, abv: 43, caskStrength: false },
  { name: "Aultmore 12", distillery: "Aultmore", region: "Speyside", type: "Single Malt", age: 12, abv: 46, caskStrength: false },
  { name: "Glentauchers 12 (Berry Bros)", distillery: "Glentauchers", region: "Speyside", type: "Single Malt", age: 12, abv: 46, caskStrength: false },

  // ─── More Highland ──────────────────────────────────────────────────────────
  { name: "Balblair 15", distillery: "Balblair", region: "Highland", type: "Single Malt", age: 15, abv: 46, caskStrength: false },
  { name: "Balblair 18", distillery: "Balblair", region: "Highland", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Balblair 25", distillery: "Balblair", region: "Highland", type: "Single Malt", age: 25, abv: 46, caskStrength: false },
  { name: "Fettercairn 12", distillery: "Fettercairn", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Fettercairn 16", distillery: "Fettercairn", region: "Highland", type: "Single Malt", age: 16, abv: 46.4, caskStrength: false },
  { name: "Fettercairn 22", distillery: "Fettercairn", region: "Highland", type: "Single Malt", age: 22, abv: 47, caskStrength: false },
  { name: "Glen Ord 12 Singleton", distillery: "Glen Ord", region: "Highland", type: "Single Malt", age: 12, abv: 40, caskStrength: false },
  { name: "Glen Ord 15 Singleton", distillery: "Glen Ord", region: "Highland", type: "Single Malt", age: 15, abv: 40, caskStrength: false },
  { name: "Glen Ord 18 Singleton", distillery: "Glen Ord", region: "Highland", type: "Single Malt", age: 18, abv: 40, caskStrength: false },
  { name: "Old Pulteney 18", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Old Pulteney Huddart", distillery: "Old Pulteney", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Wolfburn Morven", distillery: "Wolfburn", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Wolfburn Aurora", distillery: "Wolfburn", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Wolfburn Northland", distillery: "Wolfburn", region: "Highland", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Ardmore Legacy", distillery: "Ardmore", region: "Highland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Ardmore 20 (Gordon & MacPhail)", distillery: "Ardmore", region: "Highland", type: "Single Malt", age: 20, abv: 43, caskStrength: false },
  { name: "Aberfeldy 16", distillery: "Aberfeldy", region: "Highland", type: "Single Malt", age: 16, abv: 40, caskStrength: false },
  { name: "Aberfeldy 21", distillery: "Aberfeldy", region: "Highland", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "GlenGoyne 15", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 15, abv: 43, caskStrength: false },
  { name: "GlenGoyne 18", distillery: "Glengoyne", region: "Highland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Deanston Virgin Oak", distillery: "Deanston", region: "Highland", type: "Single Malt", age: null, abv: 46.3, caskStrength: false },
  { name: "Tomatin 14 Port Cask", distillery: "Tomatin", region: "Highland", type: "Single Malt", age: 14, abv: 46, caskStrength: false },
  { name: "Royal Brackla 16", distillery: "Royal Brackla", region: "Highland", type: "Single Malt", age: 16, abv: 40, caskStrength: false },
  { name: "Royal Brackla 21", distillery: "Royal Brackla", region: "Highland", type: "Single Malt", age: 21, abv: 40, caskStrength: false },
  { name: "Dalwhinnie Distillers Edition", distillery: "Dalwhinnie", region: "Highland", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Edradour 10 Signatory Vintage Cask Strength", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 10, abv: 57.6, caskStrength: true },
  { name: "Edradour Ballechin 10", distillery: "Edradour", region: "Highland", type: "Single Malt", age: 10, abv: 46, caskStrength: false },

  // ─── Island (Highland region) ───────────────────────────────────────────────
  { name: "Tobermory 12", distillery: "Tobermory", region: "Highland", type: "Single Malt", age: 12, abv: 46.3, caskStrength: false },
  { name: "Tobermory 20 Sherry Cask", distillery: "Tobermory", region: "Highland", type: "Single Malt", age: 20, abv: 46.3, caskStrength: false },
  { name: "Ledaig 10", distillery: "Tobermory", region: "Highland", type: "Single Malt", age: 10, abv: 46.3, caskStrength: false },
  { name: "Ledaig 18", distillery: "Tobermory", region: "Highland", type: "Single Malt", age: 18, abv: 46.3, caskStrength: false },
  { name: "Isle of Raasay Single Malt", distillery: "Isle of Raasay", region: "Highland", type: "Single Malt", age: null, abv: 46.4, caskStrength: false },
  { name: "Isle of Raasay Lightly Peated", distillery: "Isle of Raasay", region: "Highland", type: "Single Malt", age: null, abv: 46.4, caskStrength: false },
  { name: "Scapa Skiren", distillery: "Scapa", region: "Highland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Scapa Glansa", distillery: "Scapa", region: "Highland", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Jura 10", distillery: "Jura", region: "Highland", type: "Single Malt", age: 10, abv: 40, caskStrength: false },
  { name: "Jura 18", distillery: "Jura", region: "Highland", type: "Single Malt", age: 18, abv: 44, caskStrength: false },
  { name: "Jura Seven Wood", distillery: "Jura", region: "Highland", type: "Single Malt", age: null, abv: 42, caskStrength: false },
  { name: "Talisker 30", distillery: "Talisker", region: "Highland", type: "Single Malt", age: 30, abv: 45.8, caskStrength: false },
  { name: "Talisker Port Ruighe", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 45.8, caskStrength: false },
  { name: "Talisker 57° North", distillery: "Talisker", region: "Highland", type: "Single Malt", age: null, abv: 57, caskStrength: true },

  // ─── More Campbeltown ───────────────────────────────────────────────────────
  { name: "Springbank 21", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 21, abv: 46, caskStrength: false },
  { name: "Springbank 25", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 25, abv: 46, caskStrength: false },
  { name: "Longrow 14 Sherry Cask", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 14, abv: 57.8, caskStrength: true },
  { name: "Longrow Red 15 Pinot Noir Cask", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 15, abv: 52.1, caskStrength: true },
  { name: "Hazelburn 13 Oloroso Cask", distillery: "Springbank", region: "Campbeltown", type: "Single Malt", age: 13, abv: 47.1, caskStrength: false },
  { name: "Glen Scotia 18", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: 18, abv: 46, caskStrength: false },
  { name: "Glen Scotia 25", distillery: "Glen Scotia", region: "Campbeltown", type: "Single Malt", age: 25, abv: 48.8, caskStrength: false },
  { name: "Kilkerran 8 Cask Strength", distillery: "Glengyle", region: "Campbeltown", type: "Single Malt", age: 8, abv: 57.5, caskStrength: true },

  // ─── More Lowland ───────────────────────────────────────────────────────────
  { name: "Auchentoshan 18", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: 18, abv: 43, caskStrength: false },
  { name: "Auchentoshan 21", distillery: "Auchentoshan", region: "Lowland", type: "Single Malt", age: 21, abv: 43, caskStrength: false },
  { name: "Bladnoch 10", distillery: "Bladnoch", region: "Lowland", type: "Single Malt", age: 10, abv: 46.7, caskStrength: false },
  { name: "Bladnoch 15 Adela", distillery: "Bladnoch", region: "Lowland", type: "Single Malt", age: 15, abv: 46.7, caskStrength: false },
  { name: "Daftmill 12 Summer Batch", distillery: "Daftmill", region: "Lowland", type: "Single Malt", age: 12, abv: 46, caskStrength: false },

  // ─── Taiwanese Whisky ───────────────────────────────────────────────────────
  { name: "Kavalan Classic Single Malt", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Kavalan Concertmaster", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Kavalan Ex-Bourbon Oak", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kavalan Solist Vinho Barrique", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 57.1, caskStrength: true },
  { name: "Kavalan Solist Bourbon Cask", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 57.8, caskStrength: true },
  { name: "Kavalan Solist Sherry Cask", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 58.6, caskStrength: true },
  { name: "Kavalan Solist Port Cask", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 57.1, caskStrength: true },
  { name: "Kavalan Solist Fino Sherry", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 57.8, caskStrength: true },
  { name: "Kavalan Solist Amontillado Sherry", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 56.3, caskStrength: true },
  { name: "Kavalan Solist Pedro Ximenez Sherry", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 58.6, caskStrength: true },
  { name: "Kavalan King Car Conductor", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kavalan Podium", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Kavalan Distillery Select", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Kavalan Oloroso Sherry Oak", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Nantou Omar Bourbon Cask", distillery: "Nantou", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Nantou Omar Sherry Cask", distillery: "Nantou", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Nantou Omar Lychee Liqueur Barrel", distillery: "Nantou", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },

  // ─── World Whiskies ─────────────────────────────────────────────────────────
  { name: "Starward Nova", distillery: "Starward", region: "Other", type: "Single Malt", age: null, abv: 41, caskStrength: false },
  { name: "Starward Solera", distillery: "Starward", region: "Other", type: "Single Malt", age: null, abv: 43, caskStrength: false },
  { name: "Starward Two-Fold", distillery: "Starward", region: "Other", type: "Blended", age: null, abv: 40, caskStrength: false },
  { name: "Starward Fortis", distillery: "Starward", region: "Other", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Starward Octave Barrels", distillery: "Starward", region: "Other", type: "Single Malt", age: null, abv: 48, caskStrength: false },
  { name: "Penderyn Madeira Finish", distillery: "Penderyn", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Penderyn Sherrywood", distillery: "Penderyn", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Penderyn Rich Oak", distillery: "Penderyn", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Penderyn Portwood", distillery: "Penderyn", region: "Other", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Penderyn Myth", distillery: "Penderyn", region: "Other", type: "Single Malt", age: null, abv: 41, caskStrength: false },
  { name: "Stauning El Clasico", distillery: "Stauning", region: "Other", type: "Rye", age: null, abv: 45.7, caskStrength: false },
  { name: "Stauning Smoke", distillery: "Stauning", region: "Other", type: "Single Malt", age: null, abv: 47, caskStrength: false },
  { name: "Stauning Kaos", distillery: "Stauning", region: "Other", type: "Other", age: null, abv: 46, caskStrength: false },
  { name: "Stauning Rye", distillery: "Stauning", region: "Other", type: "Rye", age: null, abv: 48, caskStrength: false },

  // ─── More Indian ────────────────────────────────────────────────────────────
  { name: "Amrut Intermediate Sherry", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 57.1, caskStrength: true },
  { name: "Amrut Kadhambam", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Amrut Double Cask", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Amrut Portonova", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 62.1, caskStrength: true },
  { name: "Paul John Nirvana", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Paul John Kanya", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Paul John Mithuna", distillery: "Paul John", region: "Indian", type: "Single Malt", age: null, abv: 58, caskStrength: true },
  { name: "Rampur Double Cask", distillery: "Rampur", region: "Indian", type: "Single Malt", age: null, abv: 45, caskStrength: false },
  { name: "Rampur Asava", distillery: "Rampur", region: "Indian", type: "Single Malt", age: null, abv: 45, caskStrength: false },
  { name: "Indri Trini", distillery: "Indri", region: "Indian", type: "Single Malt", age: null, abv: 46, caskStrength: false },
  { name: "Indri Dru", distillery: "Indri", region: "Indian", type: "Single Malt", age: null, abv: 57.2, caskStrength: true },
  { name: "Girgaon by Goa Brewing Co.", distillery: "Girgaon", region: "Indian", type: "Single Malt", age: null, abv: 42.8, caskStrength: false },

  // ─── More Bourbon & Rye ─────────────────────────────────────────────────────
  { name: "Weller Special Reserve", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 45, caskStrength: false },
  { name: "Weller Antique 107", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 53.5, caskStrength: false },
  { name: "Weller 12", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 12, abv: 45, caskStrength: false },
  { name: "Weller Full Proof", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 57, caskStrength: true },
  { name: "Weller C.Y.P.B.", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 47.5, caskStrength: false },
  { name: "George T. Stagg", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 64.75, caskStrength: true },
  { name: "William Larue Weller", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: null, abv: 62.85, caskStrength: true },
  { name: "Thomas H. Handy Sazerac Rye", distillery: "Buffalo Trace", region: "Bourbon", type: "Rye", age: null, abv: 64.75, caskStrength: true },
  { name: "Old Forester 1920 Prohibition Style", distillery: "Old Forester", region: "Bourbon", type: "Bourbon", age: null, abv: 57.5, caskStrength: false },
  { name: "Old Forester 1910 Old Fine Whisky", distillery: "Old Forester", region: "Bourbon", type: "Bourbon", age: null, abv: 46.5, caskStrength: false },
  { name: "Old Forester Statesman", distillery: "Old Forester", region: "Bourbon", type: "Bourbon", age: null, abv: 47.5, caskStrength: false },
  { name: "Old Forester Birthday Bourbon", distillery: "Old Forester", region: "Bourbon", type: "Bourbon", age: null, abv: 52, caskStrength: false },
  { name: "Michter's 10 Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: 10, abv: 47.2, caskStrength: false },
  { name: "Michter's 10 Rye", distillery: "Michter's", region: "Bourbon", type: "Rye", age: 10, abv: 46.4, caskStrength: false },
  { name: "Michter's 20 Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: 20, abv: 57.1, caskStrength: true },
  { name: "Michter's 25 Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: 25, abv: 58.1, caskStrength: true },
  { name: "Michter's Barrel Strength Rye", distillery: "Michter's", region: "Bourbon", type: "Rye", age: null, abv: 55.2, caskStrength: true },
  { name: "Michter's Toasted Barrel Bourbon", distillery: "Michter's", region: "Bourbon", type: "Bourbon", age: null, abv: 45.7, caskStrength: false },
  { name: "Pappy Van Winkle 15", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 15, abv: 53.5, caskStrength: false },
  { name: "Pappy Van Winkle 20", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 20, abv: 45.2, caskStrength: false },
  { name: "Pappy Van Winkle 23", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 23, abv: 47.8, caskStrength: false },
  { name: "Old Rip Van Winkle 10", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 10, abv: 53.5, caskStrength: false },
  { name: "Van Winkle Special Reserve 12", distillery: "Buffalo Trace", region: "Bourbon", type: "Bourbon", age: 12, abv: 45.2, caskStrength: false },
  { name: "WhistlePig 12 Old World Rye", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: 12, abv: 43, caskStrength: false },
  { name: "WhistlePig 15 Estate Oak Rye", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: 15, abv: 46, caskStrength: false },
  { name: "WhistlePig 18 Double Malt Rye", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: 18, abv: 46, caskStrength: false },
  { name: "WhistlePig Boss Hog", distillery: "WhistlePig", region: "Bourbon", type: "Rye", age: null, abv: 57.9, caskStrength: true },
  { name: "Sazerac Rye 6", distillery: "Buffalo Trace", region: "Bourbon", type: "Rye", age: 6, abv: 45, caskStrength: false },
  { name: "Elijah Craig 18", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: 18, abv: 45, caskStrength: false },
  { name: "Henry McKenna Single Barrel BiB", distillery: "Heaven Hill", region: "Bourbon", type: "Bourbon", age: 10, abv: 50, caskStrength: false },
  { name: "Angel's Envy Bourbon", distillery: "Angel's Envy", region: "Bourbon", type: "Bourbon", age: null, abv: 43.3, caskStrength: false },
  { name: "Angel's Envy Rye", distillery: "Angel's Envy", region: "Bourbon", type: "Rye", age: null, abv: 50, caskStrength: false },
  { name: "Angel's Envy Cask Strength", distillery: "Angel's Envy", region: "Bourbon", type: "Bourbon", age: null, abv: 59.95, caskStrength: true },
  { name: "Maker's Mark Private Select", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 55.35, caskStrength: true },
  { name: "Maker's Mark Wood Finishing Series", distillery: "Maker's Mark", region: "Bourbon", type: "Bourbon", age: null, abv: 54.1, caskStrength: true },

  // ─── More Japanese ──────────────────────────────────────────────────────────
  { name: "Ichiro's Malt & Grain", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 46, caskStrength: false },
  { name: "Ichiro's Malt Wine Wood Reserve", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 46, caskStrength: false },
  { name: "Ichiro's Malt Double Distilleries", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 46.5, caskStrength: false },
  { name: "Chichibu The Floor Malted", distillery: "Chichibu", region: "Japanese", type: "Japanese", age: null, abv: 50.5, caskStrength: false },
  { name: "Eigashima Akashi Single Malt 5", distillery: "Eigashima", region: "Japanese", type: "Japanese", age: 5, abv: 50, caskStrength: false },
  { name: "Eigashima White Oak Tokinoka", distillery: "Eigashima", region: "Japanese", type: "Japanese", age: null, abv: 40, caskStrength: false },
  { name: "Akkeshi Peated Single Malt Kanro", distillery: "Akkeshi", region: "Japanese", type: "Japanese", age: null, abv: 55, caskStrength: true },
  { name: "Akkeshi Blended Whisky Usui", distillery: "Akkeshi", region: "Japanese", type: "Japanese", age: null, abv: 48, caskStrength: false },
  { name: "Akkeshi Single Malt Boshu", distillery: "Akkeshi", region: "Japanese", type: "Japanese", age: null, abv: 55, caskStrength: true },
  { name: "Akkeshi Single Malt Keichitsu", distillery: "Akkeshi", region: "Japanese", type: "Japanese", age: null, abv: 55, caskStrength: true },
  { name: "Nagahama Single Malt Oloroso Sherry Cask", distillery: "Nagahama", region: "Japanese", type: "Japanese", age: null, abv: 47, caskStrength: false },
  { name: "Nagahama Single Malt Bourbon Cask", distillery: "Nagahama", region: "Japanese", type: "Japanese", age: null, abv: 47, caskStrength: false },
  { name: "Nagahama Amahagan Edition No.3 Mizunara", distillery: "Nagahama", region: "Japanese", type: "Japanese", age: null, abv: 47, caskStrength: false },
  { name: "Nikka Yoichi 15", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 15, abv: 45, caskStrength: false },
  { name: "Nikka Miyagikyo 12", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 12, abv: 45, caskStrength: false },
  { name: "Nikka Taketsuru 17", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 17, abv: 43, caskStrength: false },
  { name: "Nikka Taketsuru 21", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 21, abv: 43, caskStrength: false },
  { name: "Nikka Taketsuru 25", distillery: "Nikka", region: "Japanese", type: "Japanese", age: 25, abv: 43, caskStrength: false },
  { name: "Hibiki Blender's Choice", distillery: "Suntory", region: "Japanese", type: "Japanese", age: null, abv: 43, caskStrength: false },
  { name: "Yamazaki Puncheon", distillery: "Yamazaki", region: "Japanese", type: "Japanese", age: null, abv: 48, caskStrength: false },
  { name: "Mars Komagatake Limited Edition", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 48, caskStrength: false },
  { name: "Mars Tsunuki The First", distillery: "Mars Shinshu", region: "Japanese", type: "Japanese", age: null, abv: 59, caskStrength: true },
  { name: "Kirin Fuji Single Grain", distillery: "Fuji Gotemba", region: "Japanese", type: "Japanese", age: null, abv: 46, caskStrength: false },

  // ─── More Irish ─────────────────────────────────────────────────────────────
  { name: "Method and Madness Single Grain", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Method and Madness Single Malt", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Method and Madness Single Pot Still", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Dingle Single Malt Batch No.5", distillery: "Dingle", region: "Irish", type: "Irish", age: null, abv: 46.5, caskStrength: false },
  { name: "Dingle Single Pot Still", distillery: "Dingle", region: "Irish", type: "Irish", age: null, abv: 46.5, caskStrength: false },
  { name: "Waterford Sheestown Edition 1.1", distillery: "Waterford", region: "Irish", type: "Irish", age: null, abv: 50, caskStrength: false },
  { name: "Waterford The Cuvee", distillery: "Waterford", region: "Irish", type: "Irish", age: null, abv: 50, caskStrength: false },
  { name: "Waterford Fenniscourt Peated", distillery: "Waterford", region: "Irish", type: "Irish", age: null, abv: 50, caskStrength: false },
  { name: "Tyrconnell 10 Madeira Cask", distillery: "Cooley", region: "Irish", type: "Irish", age: 10, abv: 46, caskStrength: false },
  { name: "Tyrconnell 10 Port Cask", distillery: "Cooley", region: "Irish", type: "Irish", age: 10, abv: 46, caskStrength: false },
  { name: "Tyrconnell 10 Sherry Cask", distillery: "Cooley", region: "Irish", type: "Irish", age: 10, abv: 46, caskStrength: false },
  { name: "Tyrconnell 16", distillery: "Cooley", region: "Irish", type: "Irish", age: 16, abv: 46, caskStrength: false },
  { name: "Redbreast 27", distillery: "Midleton", region: "Irish", type: "Irish", age: 27, abv: 54.6, caskStrength: true },
  { name: "Green Spot Chateau Montelena", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Green Spot Chateau Leoville Barton", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Blue Spot 7", distillery: "Midleton", region: "Irish", type: "Irish", age: 7, abv: 58.7, caskStrength: true },
  { name: "Red Spot 15", distillery: "Midleton", region: "Irish", type: "Irish", age: 15, abv: 46, caskStrength: false },
  { name: "Teeling Small Batch", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },
  { name: "Teeling 24 Vintage Reserve", distillery: "Teeling", region: "Irish", type: "Irish", age: 24, abv: 46, caskStrength: false },
  { name: "Teeling Brabazon Bottling Series 2", distillery: "Teeling", region: "Irish", type: "Irish", age: null, abv: 49.5, caskStrength: false },
  { name: "Midleton Very Rare", distillery: "Midleton", region: "Irish", type: "Irish", age: null, abv: 40, caskStrength: false },
  { name: "Bushmills 12 Distillery Reserve", distillery: "Bushmills", region: "Irish", type: "Irish", age: 12, abv: 40, caskStrength: false },
  { name: "Bushmills Causeway Collection 2001 Madeira", distillery: "Bushmills", region: "Irish", type: "Irish", age: null, abv: 46, caskStrength: false },

  // ─── More Blends & Blended Malts ────────────────────────────────────────────
  { name: "Johnnie Walker 18 Ultimate", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: 18, abv: 40, caskStrength: false },
  { name: "Johnnie Walker King George V", distillery: "Johnnie Walker", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box Orchard House", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box Glasgow Blend", distillery: "Compass Box", region: "Other", type: "Blended", age: null, abv: 43, caskStrength: false },
  { name: "Compass Box The Circle No.1", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 46, caskStrength: false },
  { name: "Compass Box No Name No.3", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 48.9, caskStrength: false },
  { name: "Compass Box Flaming Heart", distillery: "Compass Box", region: "Other", type: "Blended Malt", age: null, abv: 48.9, caskStrength: false },
  { name: "Chivas Regal Ultis", distillery: "Chivas", region: "Other", type: "Blended Malt", age: null, abv: 40, caskStrength: false },
  { name: "Chivas Regal 25", distillery: "Chivas", region: "Other", type: "Blended", age: 25, abv: 40, caskStrength: false },
  { name: "Royal Salute 21", distillery: "Chivas", region: "Other", type: "Blended", age: 21, abv: 40, caskStrength: false },
  { name: "Ballantine's 30", distillery: "Ballantine's", region: "Other", type: "Blended", age: 30, abv: 40, caskStrength: false },
  { name: "Dewar's 18", distillery: "Dewar's", region: "Other", type: "Blended", age: 18, abv: 40, caskStrength: false },
  { name: "Big Peat 25", distillery: "Douglas Laing", region: "Islay", type: "Blended Malt", age: 25, abv: 52.1, caskStrength: true },
  { name: "Scallywag 13", distillery: "Douglas Laing", region: "Speyside", type: "Blended Malt", age: 13, abv: 46, caskStrength: false },
  { name: "Epicurean", distillery: "Douglas Laing", region: "Lowland", type: "Blended Malt", age: null, abv: 46.2, caskStrength: false },
  { name: "Hakushu 25", distillery: "Hakushu", region: "Japanese", type: "Japanese", age: 25, abv: 43, caskStrength: false },
  { name: "Glenfiddich 26 Grande Couronne", distillery: "Glenfiddich", region: "Speyside", type: "Single Malt", age: 26, abv: 43.8, caskStrength: false },
  { name: "Bowmore Vault Edition First Release", distillery: "Bowmore", region: "Islay", type: "Single Malt", age: null, abv: 51.5, caskStrength: true },
  { name: "Balvenie 25 Single Barrel", distillery: "Balvenie", region: "Speyside", type: "Single Malt", age: 25, abv: 47.8, caskStrength: false },
  { name: "Starward Left-Field", distillery: "Starward", region: "Other", type: "Single Malt", age: null, abv: 40, caskStrength: false },
  { name: "Amrut Spectrum 004", distillery: "Amrut", region: "Indian", type: "Single Malt", age: null, abv: 50, caskStrength: false },
  { name: "Kavalan Solist Peated Malt", distillery: "Kavalan", region: "Other", type: "Single Malt", age: null, abv: 54.8, caskStrength: true },
  { name: "Macallan Harmony Collection Rich Cacao", distillery: "Macallan", region: "Speyside", type: "Single Malt", age: null, abv: 44, caskStrength: false },
  { name: "Dalmore 25", distillery: "Dalmore", region: "Highland", type: "Single Malt", age: 25, abv: 42, caskStrength: false },
];
